language: csharp
solution: EPerez_300911292_A3.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore EPerez_300911292_A3.sln
after_script:
  - nunit-console SwimTest/bin/Debug/SwimTest.dll
