language: csharp
solution: EPerez_300911292_A3.sln
install:
  - nuget restore EPerez_300911292_A3.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release EPerez_300911292_A3.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SwimTest/bin/Release/SwimTest.dll
